=== Meta-Platform/meta-platform-applications-repository/Apps.Module/Tools.layer/PackageDeveloper.group/package-developer.webapp/metadata/startup-params-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "installDataDirPath": {
      "type": "string"
    },
    "port": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "serverName": {
      "type": "string"
    },
    "serverManagerUrl": {
      "type": "string",
      "format": "uri"
    },
    "workspaceStorageFilePath": {
      "type": "string"
    },
    "runCommandPath": {
      "type": "string"
    }
  },
  "required": [
    "port",
    "serverName",
    "serverManagerUrl",
    "workspaceStorageFilePath",
    "runCommandPath"
  ]
}

=== Meta-Platform/meta-platform-applications-repository/Apps.Module/Tools.layer/PackageDeveloper.group/package-developer.webapp/metadata/startup-params.json
{
    "installDataDirPath":"~/EcosystemData",
    "port":"8093",
    "serverName":"PackageDeveloperWebappInstance",
    "serverManagerUrl": "http://localhost:8093/server-manager/status",
    "workspaceStorageFilePath":"~/virtual-desk-state/local-databases/package-developer-workspace-store-service.sqlite",
    "runCommandPath":"/home/kadisk/EcosystemData/executables/run"
}
